# permissions for end users to view cockroachdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cockroachdb-viewer-role
rules:
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - cockroachdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - cockroachdbs/status
  verbs:
  - get
